In [0]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [0]:
AF=pd.read_csv('AF_csv_14972.csv')

In [0]:
AF.head()

Unnamed: 0             0             1  ...       198       199  Lable
0           0  4.360680e-08  6.410188e-07  ... -0.000586 -0.000554      1
1           1 -9.809577e-08 -1.426375e-06  ... -0.000320 -0.000275      1
2           2  4.653737e-08  6.958202e-07  ... -0.000293 -0.000261      1
3           3 -8.002395e-08 -1.164628e-06  ... -0.000420 -0.000380      1
4           4 -8.000442e-08 -1.183878e-06  ...  0.002297  0.002666      1

[5 rows x 202 columns]

In [0]:
AF.drop('Unnamed: 0', axis=1, inplace=True)
#AF.rename(columns={'Unnamed: 0':'ID'}, inplace=True)
#AF['Lable']='AF'

In [0]:
AF.head(), AF.shape

(              0             1         2  ...       198       199  Lable
 0  4.360680e-08  6.410188e-07  0.000004  ... -0.000586 -0.000554      1
 1 -9.809577e-08 -1.426375e-06 -0.000010  ... -0.000320 -0.000275      1
 2  4.653737e-08  6.958202e-07  0.000005  ... -0.000293 -0.000261      1
 3 -8.002395e-08 -1.164628e-06 -0.000008  ... -0.000420 -0.000380      1
 4 -8.000442e-08 -1.183878e-06 -0.000008  ...  0.002297  0.002666      1
 
 [5 rows x 201 columns], (14972, 201))

In [0]:
AF.iloc[:,1]

0        6.410188e-07
1       -1.426375e-06
2        6.958202e-07
3       -1.164628e-06
4       -1.183878e-06
             ...     
14967   -1.862840e-07
14968   -6.909301e-07
14969    1.773731e-07
14970   -8.734199e-07
14971    1.863871e-06
Name: 1, Length: 14972, dtype: float64

In [0]:
AF_final=AF.iloc[0:14500,:]

In [0]:
AF_final.head(),AF_final.shape

(              0             1         2  ...       198       199  Lable
 0  4.360680e-08  6.410188e-07  0.000004  ... -0.000586 -0.000554      1
 1 -9.809577e-08 -1.426375e-06 -0.000010  ... -0.000320 -0.000275      1
 2  4.653737e-08  6.958202e-07  0.000005  ... -0.000293 -0.000261      1
 3 -8.002395e-08 -1.164628e-06 -0.000008  ... -0.000420 -0.000380      1
 4 -8.000442e-08 -1.183878e-06 -0.000008  ...  0.002297  0.002666      1
 
 [5 rows x 201 columns], (14500, 201))

In [0]:
normal=pd.read_csv('Normal_csv_48600.csv')
#N1=pd.read_csv('Dataset_16265_sets_1149.csv')
#N2=AF=pd.read_csv('Dataset_16265_sets_2500.csv')

In [0]:
normal.drop('Unnamed: 0', axis=1, inplace=True)
#N1.drop('Unnamed: 0', axis=1, inplace=True)
#N2.drop('Unnamed: 0', axis=1, inplace=True)

In [0]:
normal.head(),normal.shape

(              0             1             2  ...       198       199  Lable
 0 -9.258724e-08 -1.377041e-06 -9.609210e-06  ... -0.002655 -0.001942      0
 1 -8.846425e-08 -1.300422e-06 -8.939689e-06  ...  0.000270  0.000335      0
 2 -3.962878e-09 -5.825420e-08 -4.099061e-07  ... -0.000354 -0.000313      0
 3 -9.887181e-09 -1.373355e-07 -8.690240e-07  ...  0.000308  0.000389      0
 4 -6.748902e-08 -1.024110e-06 -7.339241e-06  ... -0.001400 -0.001010      0
 
 [5 rows x 201 columns], (48599, 201))

In [0]:
#N1.head(),N1.shape
#N2.head(), N2.shape
#normal=N1.append(N2)
#normal['Lable']='N'
#normal.head(), normal.shape
#normal_extd=pd.concat([normal]*3, ignore_index=True)
#normal_extd.shape
#normal_final=normal_extd.iloc[0:10000,:]

In [0]:
normal_final=normal.iloc[0:14500,:]

In [0]:
normal_final.head(), normal_final.shape

(              0             1             2  ...       198       199  Lable
 0 -9.258724e-08 -1.377041e-06 -9.609210e-06  ... -0.002655 -0.001942      0
 1 -8.846425e-08 -1.300422e-06 -8.939689e-06  ...  0.000270  0.000335      0
 2 -3.962878e-09 -5.825420e-08 -4.099061e-07  ... -0.000354 -0.000313      0
 3 -9.887181e-09 -1.373355e-07 -8.690240e-07  ...  0.000308  0.000389      0
 4 -6.748902e-08 -1.024110e-06 -7.339241e-06  ... -0.001400 -0.001010      0
 
 [5 rows x 201 columns], (14500, 201))

In [0]:
VF=pd.read_csv('VF_csv_57751.csv')

In [0]:
VF.drop('Unnamed: 0', axis=1, inplace=True)

In [0]:
#VF['Lable']='VF'

In [0]:
VF.head(), VF.shape

(              0             1             2  ...       198       199  Lable
 0 -3.237869e-10 -6.876113e-09 -7.149320e-08  ...  0.002340  0.002407      2
 1  6.174944e-10  1.246987e-08  1.232952e-07  ...  0.002222  0.002386      2
 2  5.592542e-10  1.136125e-08  1.130622e-07  ...  0.001249  0.001298      2
 3  5.469068e-10  1.111797e-08  1.106763e-07  ... -0.000651 -0.000613      2
 4 -1.468383e-10 -2.917256e-09 -2.833324e-08  ...  0.001857  0.001897      2
 
 [5 rows x 201 columns], (57750, 201))

In [0]:
VF_final=VF.iloc[0:14500,:]

In [0]:
VF_final.head(), VF_final.shape

(              0             1             2  ...       198       199  Lable
 0 -3.237869e-10 -6.876113e-09 -7.149320e-08  ...  0.002340  0.002407      2
 1  6.174944e-10  1.246987e-08  1.232952e-07  ...  0.002222  0.002386      2
 2  5.592542e-10  1.136125e-08  1.130622e-07  ...  0.001249  0.001298      2
 3  5.469068e-10  1.111797e-08  1.106763e-07  ... -0.000651 -0.000613      2
 4 -1.468383e-10 -2.917256e-09 -2.833324e-08  ...  0.001857  0.001897      2
 
 [5 rows x 201 columns], (14500, 201))

In [0]:
dataset=normal_final
dataset=dataset.append(AF_final, sort=False)
dataset=dataset.append(VF_final, sort=False)

In [0]:
dataset.shape

(43500, 201)

In [0]:
#dataset.drop('Unnamed: 0', axis=1, inplace=True)
#dataset.drop('ID', axis=1, inplace=True)

In [0]:
dataset.Lable.unique()

array([0, 1, 2])

In [0]:
dataset.iloc[:,200]

0        0
1        0
2        0
3        0
4        0
        ..
14495    2
14496    2
14497    2
14498    2
14499    2
Name: Lable, Length: 43500, dtype: int64

In [0]:
#AF_Final=AF_final.values
#NORMAL_Final=normal_final.values
#VF_Final=VF_final.values

Dataset=dataset.values

In [0]:
#AF_Final, NORMAL_Final, VF_Final
Dataset, Dataset.shape

(array([[-9.25872441e-08, -1.37704149e-06, -9.60921015e-06, ...,
         -2.65492174e-03, -1.94216488e-03,  0.00000000e+00],
        [-8.84642497e-08, -1.30042196e-06, -8.93968939e-06, ...,
          2.70092179e-04,  3.35490175e-04,  0.00000000e+00],
        [-3.96287815e-09, -5.82541964e-08, -4.09906064e-07, ...,
         -3.53863385e-04, -3.12560791e-04,  0.00000000e+00],
        ...,
        [ 1.56276773e-11,  3.15746759e-10,  3.09847478e-09, ...,
         -3.04340273e-04, -2.15974928e-04,  2.00000000e+00],
        [ 1.09208066e-10,  2.23123258e-09,  2.23752191e-08, ...,
          6.21093405e-04,  6.86054633e-04,  2.00000000e+00],
        [ 1.39318423e-10,  2.79626792e-09,  2.74432436e-08, ...,
          4.36727284e-04,  3.27692855e-04,  2.00000000e+00]]), (43500, 201))

In [0]:
np.random.shuffle(Dataset)
np.random.shuffle(Dataset)
np.random.shuffle(Dataset)

In [0]:
Dataset[12000]

array([-5.59316120e-10, -1.12572835e-08, -1.10893049e-07, -7.13595723e-07,
       -3.37777662e-06, -1.25545919e-05, -3.81886851e-05, -9.78078619e-05,
       -2.15288436e-04, -4.13469666e-04, -7.00614017e-04, -1.05570910e-03,
       -1.42153484e-03, -1.71345251e-03, -1.84489055e-03, -1.76076638e-03,
       -1.46355438e-03, -1.01807280e-03, -5.30409334e-04, -1.08976732e-04,
        1.75275548e-04,  3.11787092e-04,  3.46710421e-04,  3.55373082e-04,
        4.04418692e-04,  5.21218554e-04,  6.83848534e-04,  8.34700863e-04,
        9.09729991e-04,  8.68641969e-04,  7.11921306e-04,  4.77748815e-04,
        2.21830920e-04, -8.93570432e-06, -1.95817396e-04, -3.51678802e-04,
       -5.07900850e-04, -6.92468351e-04, -9.11107172e-04, -1.14145986e-03,
       -1.34333750e-03, -1.47962731e-03, -1.53679844e-03, -1.53404236e-03,
       -1.51588297e-03, -1.53160972e-03, -1.61171689e-03, -1.75314965e-03,
       -1.92075506e-03, -2.06421097e-03, -2.14201615e-03, -2.14073088e-03,
       -2.08018131e-03, -

In [0]:
train, test1 = train_test_split(Dataset, test_size=0.3)

In [0]:
train.shape

(30450, 201)

In [0]:
test1.shape

(13050, 201)

In [0]:
#train.Embarked.values_counts()

In [0]:
validation, test = train_test_split(test1, test_size=0.5)

In [0]:
train.shape, validation.shape, test.shape

((30450, 201), (6525, 201), (6525, 201))

In [0]:
Train = pd.DataFrame(data=train)
Validation=pd.DataFrame(data=validation)
Test=pd.DataFrame(data=test)

In [0]:
Train.head(), Train.shape

(            0             1             2    ...       198       199  200
 0 -1.093257e-09 -2.207614e-08 -2.182277e-07  ...  0.002305  0.002206  2.0
 1 -8.943364e-12 -1.559380e-10 -1.274783e-09  ...  0.000185  0.000195  2.0
 2 -1.520304e-07 -2.234843e-06 -1.541836e-05  ...  0.007477  0.011275  0.0
 3 -8.358070e-08 -1.212622e-06 -8.241071e-06  ...  0.000061  0.000293  0.0
 4 -9.936568e-08 -1.468488e-06 -1.018436e-05  ... -0.000077 -0.000151  1.0
 
 [5 rows x 201 columns], (30450, 201))

In [0]:
Validation.head(), Validation.shape

(            0             1         2    ...       198       199  200
 0 -5.058155e-08 -6.888434e-07 -0.000004  ... -0.000086 -0.000118  1.0
 1 -1.560623e-07 -2.290205e-06 -0.000016  ... -0.000940 -0.000815  1.0
 2  1.931403e-07  2.486901e-06  0.000014  ... -0.000228 -0.000370  0.0
 3  4.933117e-08  6.978149e-07  0.000005  ...  0.000224  0.000216  1.0
 4 -1.738062e-07 -2.522923e-06 -0.000017  ... -0.000371 -0.000403  0.0
 
 [5 rows x 201 columns], (6525, 201))

In [0]:
Test.head(), Test.shape

(            0             1             2    ...       198       199  200
 0 -1.965237e-07 -2.904522e-06 -2.012138e-05  ... -0.000041 -0.000062  1.0
 1 -8.558216e-08 -1.250049e-06 -8.553730e-06  ... -0.000526 -0.000523  0.0
 2  2.320942e-11  4.813092e-10  4.938072e-09  ...  0.000369  0.000281  2.0
 3 -8.954503e-08 -1.308304e-06 -8.971642e-06  ... -0.000670 -0.000513  0.0
 4 -1.176054e-07 -1.640732e-06 -1.061655e-05  ... -0.000127 -0.000015  0.0
 
 [5 rows x 201 columns], (6525, 201))

In [0]:
Train.to_csv('trainset.csv')

In [0]:
Validation.to_csv('validset.csv')

In [0]:
Test.to_csv('testset.csv')

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive
